### ISSUE TITLE
Empty character sheet

### ISSUE THREAD

**Issue by brunobord** [kgrubb/microluxe20#14]
I've downloaded this file: https://github.com/kgrubb/microluxe20/releases/download/1.5.0/microluxe20_1.5.0.zip

and the document ``microluxe20-cs.pdf`` is empty (zero byte). Looks like something's wrong in the 1.5 release...

**Comment by kgrubb** [comment]
Thanks for the heads up, I'll get that fixed asap! In the meantime, the character sheet can still be downloaded from github or from an earlier release.

**Comment by kgrubb** [comment]
Alright, the release has been fixed.

https://github.com/kgrubb/microluxe20/releases/download/1.5.0/microluxe20_1.5.0.zip
should have the correct `microluxe20-cs.pdf` file now, instead of an empty file.

**Comment by brunobord** [comment]
thx, that was a quick fix!
