### ISSUE TITLE
[Tooling Suggestion] Split Handbook into multiple topical files

### ISSUE THREAD

**Issue by Web-eWorks** [kgrubb/microluxe20#24]
At the moment, the Handbook is a slightly unwieldy ~1600 lines and 92KB. I think there might be some benefit to splitting the Handbook up into several smaller topical documents.

My initial thought is to split the spell, equipment, and/or monster lists into their own document (or documents), much like the races and lore documents. I'm not 100% sold on the idea yet, but I figured I'd put it out there for perusal.

**Comment by kgrubb** [comment]
This could also help some of the div stuff possibly. For example, each section can be its own md file (so its easy to know where to edit things in src) and the compile section can pipe the md files together in the end to create one single document for printing.

**Comment by Web-eWorks** [comment]
Ancillary to that, can you (I'm assuming you have it) commit the Microluxe logo image without the document title text? I'd like to construct the title pages out of Markdown as much as possible, to avoid asset duplication.

With some CSS for a title `div`+`h1` and the plain logo image, there's no need for three different title page images like we have now.

**Comment by kgrubb** [comment]
good point. I added the logo's svg in the [src dir](https://github.com/kgrubb/microluxe20/blob/master/src/static/logo.svg).

**Comment by Web-eWorks** [comment]
Well, let me finish up with my current batch of improvements, and I'll get on that.

**Comment by Web-eWorks** [comment]
Well, somewhere in the markdownpdf stack, something doesn't like `@import` fonts, because Trade Winds refuses to load itself. I messed around with constructing the title cards out of a logo image + text and got this out of the bargain:

![screenshot from 2017-07-30 16-24-59](https://user-images.githubusercontent.com/4218491/28756804-c1599e54-7543-11e7-92fd-f0187ae6f608.png)

But then I realized that the Github display doesn't hook into the CSS file, so this styling is going to look mighty awkward when not in a PDF.

**Comment by kgrubb** [comment]
Can you push out the changes when you feel good about them? I'd be curious to play around with the font stack. If it's not fixable on the GitHub side, it may be time to move the online docs to something like a Jekyll blog. I've just been kind of lazy and didn't want to spend time on setting up a Jekyll site.

**Comment by Web-eWorks** [comment]
https://github.com/Web-eWorks/microluxe20/tree/titlecards

It's not pretty - markdownpdf wouldn't take the SVG file from github, so all the image links are local to the root directory for debugging.

**Comment by Web-eWorks** [comment]
Well, I found and fixed the problem with the fonts. Seems PhantomJS doesn't want to load any external assets, so I had to store the font file locally. It'll need a license document, but it works now.

**Comment by Web-eWorks** [comment]
How attached are you to piping everything together? I understand wanting a single document for printing, but honestly the monster, spell, and equipment lists don't really need to be in the main document.

I've been playing around with splitting the classes and their spells into a separate document, allowing us to go into more detail about each class without cluttering up the main section. Obviously, I'd keep a short description in the character creation section for functionality.

**Comment by kgrubb** [comment]
I'm completely fine with splitting everything into multiple topical files for development and writing. That's probably the direction we need to go. 🥇 

However, I'd like to have the printable document as a single doc still, so that its one single pdf file to print out. Concatenating all of the files should be pretty easy to do in just the compile/release steps (or maybe we only pipe in the release step? not sure yet). Perhaps we can also make a secondary download available with each topical file remaining separated as well, for people that would prefer many smaller docs instead of one larger doc? I'm definitely open to suggestion.

One more thing I'd like to bring up is page-length. Currently, we are at approx 32 single-side pages. While we add/remove/modify the docs, I'd prefer to try and keep our total `handbook + monster_manual + gm_guide` page-size to 35 pages max, since the game is intended to be a small, lightweight game.

**Comment by Web-eWorks** [comment]
Would it be possible to split it into a Player's Handbook (rules, spells, equipment) and a Gamemaster's Guide (monster list, traps, poisons, designer's notes)? If people want it in a single paper document, they can print out both and staple them together. My rationale here is that people printing it out are most likely doing it to distribute to players, and not duplicating the GM's section in players' copies saves paper, ink, and time.

I'd say having a multifile download and either a unified or bisected model works well. The proposed page length sounds good. I may toy around with putting character spells in a table instead of the current, extremely long format, which should help with that.

Regarding your concerns raised in #37, I think moving to a GH Pages site is the way to go.

**Comment by kgrubb** [comment]
Yeah, this all sounds good to me! :+1: I think we should go forward with a multifile dl, a bisected model (ph & gmg), and push for an updated/dynamic gh-pages site for online viewing. I'll try and make a gh project to plan & view the various changes we'll need to implement.
