### ISSUE TITLE
Stat Damage

### ISSUE THREAD

**Issue by Web-eWorks** [kgrubb/microluxe20#26]
An interesting conundrum - some monsters and attacks in the SRD deal damage directly to stats.

Shadows, for example, deal 1d6 damage directly to the STR stat, and when it reaches 0, the character dies. (Stats are restored after a full rest, I'm assuming)

In the SRD, this is reasonably balanced, as (from what I remember of 5e character creation) stats are in the 8-15 range _at creation_ - rather well outside of the range of even a 10th level Fighter in Microluxe.

Currently, I think the way I'm going to handle this in my game is to make Incorporeal Touch an automatic-hit attack dealing 1d6 normal damage, and requiring a STR save against a certain DC to resist the damage, though I'm open to suggestions.

**Comment by kgrubb** [comment]
would dealing 1d6/2 (round down) stat damage work? I think the normal damage with a save to resist is a pretty safe way to convert the overpowering stat drains in an SRD -> m20 conversion.

**Comment by Web-eWorks** [comment]
My party's probably going to be running into a couple of shadows here in the next few sessions, so I'll try to get some playtesting in. I'm leaning more towards the save route, as it gives saves something to actually do in Microluxe.

One thought I had was that (as I see it) stats in Microluxe (unlike SRD), have 0 as the 'bog-standard human' baseline, rather than 'none at all'. Perhaps there's a stat minimum - say `0 - (8 + nominal STAT bonus)` - that is the death level instead. Getting your stats reduced to below zero incurs a negative stat bonus (bonus = stat / 2, rounding towards negative infinity) until a 4 hour rest at which point stats are returned to the normal (positive) level.

**Comment by Web-eWorks** [comment]
After some further consideration (and very little playtesting, my party dispatched the shadow encounter in three rounds), I have come to a solution that might work.

Stat damage attacks work like normal attacks, but have a save vs. DC to resist for half damage. If a stat drops to -10, the character is rendered unconscious, and the 0 HP rules apply. After a four-hour rest, the character's stats are returned to normal. A negative stat bonus subtracts from a roll rather than add to it, obviously.

This brings things fairly in line with the SRD (a fighter with 6 STR has an effective stat of 16), and has a minimum of magic numbers or calculations attached.

**Comment by kgrubb** [comment]
:+1: this sounds like a great solution to me! Mind making a pr? I'll test this out in a playtest this week and make sure things work properly (although I can't currently see how this could break). :tada:

**Comment by Web-eWorks** [comment]
PR incoming either today or later this week.

**Comment by Web-eWorks** [comment]
PR dropped (#33). Recommend marking this for 1.7.4.

**Comment by kgrubb** [comment]
Merged in #33. This will ship with 1.7.4
