### ISSUE TITLE
Clarify Spell Component/Requirements

### ISSUE THREAD

**Issue by kgrubb** [kgrubb/microluxe20#31]
As discussed in #23, there is a single sentence regarding spell components being an item requirement, but _thats it_. They're not referenced or explained anywhere else. This is a remnant from SRD based rules that hung around to make things easy to convert, but instead, makes things confusing/difficult.

For microluxe20, either remove spell components entirely or add a tiny section including information on what spell components are and why they'd be required for a spellcaster.

**Comment by Web-eWorks** [comment]
If there's no objection, I would suggest removing them entirely. If required by the setting, GMs can add them back in with absolutely no difficulty.

**Comment by kgrubb** [comment]
:+1: no objections here. I personally have not used them or referenced them in any games that I've played.

**Comment by Web-eWorks** [comment]
As an aside, there really needs to be a better way to store the equipment tables. Editing a table that large in markdown is a royal pain.
