### ISSUE TITLE
[Tooling] Move Equipment Tables to Editable Format

### ISSUE THREAD

**Issue by Web-eWorks** [kgrubb/microluxe20#37]
Multi-column tables, as currently implemented, are extremely painful to edit in Markdown. I propose (in concert with #24) moving the various tables into an external file written in YAML (or similar easy-to-edit data language, so not JSON), and having the build process convert them into Markdown or even straight HTML tables.

**Comment by Web-eWorks** [comment]
For reference, here's a mockup of the system. There will be a processor that looks for comments in the markdown starting with `!data`, which loads the appropriate YAML file and formats and inserts the table as required. Not pictured: the `columns` key in the YAML which allows controlling how many combined columns to generate.

Personally, I think it makes it much easier to read and edit, though it will require hosting the pages manually, as the tables will not be included on the current github view.

![image](https://user-images.githubusercontent.com/4218491/35539234-c33adc04-051e-11e8-9e20-d432e7f80e1e.png)

**Comment by Web-eWorks** [comment]
See [this commit](https://github.com/Web-eWorks/microluxe20/commit/8f6d98e63dd55f22ba3bf1dde4960056bd2011d8) for the implementation; it's currently throwing a `Write after end` error after processing some documents. Improvements are very welcome, I do not use JS much.

**Comment by kgrubb** [comment]
I agree that this is a pain point. My only issue with going the yml route is that it removes the ability to view the rules/tables online via github. If we move to this, I think we'd also need to have a way to allow for online viewing of the rules. This could maybe be accomplished via a github pages jekyll-based server.

**Comment by Web-eWorks** [comment]
Closed by #42. Finally!
